---
knit: "bookdown::render_book"
title: "That's weird: Anomaly&nbsp;detection&nbsp;using&nbsp;R"
author:
  name: "Rob J Hyndman"
  affiliation: Monash University, Australia
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    highlight: tango
bibliography: [weird.bib]
biblio-style: authoryear-comp
geometry: left=1.3cm
subparagraph: yes
link-citations: yes
url: 'https\://Otexts.com/weird/'
twitter-handle: robjhyndman
---

# Preface {-}

> This book is under development. Please don't ask me when it will be finished --- I have to fit this around my other work. In the meantime, I hope the incomplete book is useful.

Data analysis is about finding the stories hidden in the mass of information that make up a data set. Usually we are interested in understanding the major patterns --- the relationships that describe how most of the data behave. But sometimes we need to look at the weird observations --- the data that doesn't follow the crowd and behaves differently. We call these weird observations "anomalies". They are the mavericks in the data.

Anomalies are often a nuisance. For example, they may be simply recording errors that are contaminating our data. We want to find them, remove them, and get on with analysing the bulk of the data. At other times, anomalies are the interesting observations. They tell us things that might otherwise go unnoticed if we only consider how the majority of observations behave.

This book is about tools and techniques for finding and understanding anomalies. We will begin with some simple data sets with only one variable, and build up slowly to much more complicated data.

The book is written for two audiences: (1)&nbsp;people finding themselves doing data analysis in business when they may not have had any formal training in the area; and (2)&nbsp;students studying data science.

I will assume a knowledge of statistics and probability at about second year undergraduate level. So if you've done a couple of statistics subjects, and are familiar with multiple regression, hypothesis tests and probability distributions, then you should be prepared for what follows.

### R {-}

I will also assume you already know how to use R and are familiar with the [tidyverse](https://tidyverse.org) packages such as `dplyr`, `tidyr` and `ggplot2`.

All R examples in the book assume you have loaded the `weird` package first:

```{r library, eval=FALSE}
#WARNING: This package is still private.
#remotes::install_github("robjhyndman/weird-package")
library(weird)
```

This will load the relevant data sets and functions from the packages needed to reproduce the examples.

### Outline {-}

1. Introduction
2. Tools
3. One dimensional methods
4. Bivariate methods
5. Multivariate methods
6. Non-euclidean spaces
7. Time series anomalies
8. Spatial, network and graph data
9. Video data
10. Categorical and text data
11. Applications: network intrusion, fraud detection


### References {-}

- [https://github.com/pridiltal/ctv-AnomalyDetection](https://github.com/pridiltal/ctv-AnomalyDetection)
-

### Examples {-}

- Don Bradman average
- Old Faithful eruption durations: [https://geysertimes.org/archive/](https://geysertimes.org/archive/)
- US crime data
- [https://sevvandi.netlify.app/post/2021-01-23-anomaly-detection-datasets/](https://sevvandi.netlify.app/post/2021-01-23-anomaly-detection-datasets/)
- [https://github.com/rfordatascience/tidytuesday](https://github.com/rfordatascience/tidytuesday)
-
