<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.3">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Time series data – That's weird! Anomaly&nbsp;detection using&nbsp;R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-functional.html" rel="next">
<link href="./08-highdim.html" rel="prev">
<link href="./favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-38c29600923cc2366e56826496234dd0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-44e9592805011dbfda54dd16badca160.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-timeseries.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Time series data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">That’s weird! Anomaly&nbsp;detection using&nbsp;R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-univariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Univariate probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multivariate probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistical tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-boxplots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Boxplots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-density.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Density-based methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-distance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Distance-based methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-highdim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">High-dimensional methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-timeseries.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Time series data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-functional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Functional data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-network.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Network and graph data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-imagevideo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Image and video data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Categorical and textual data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Spaces of probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-cybersecurity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Network intrusions and fraud</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliography</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Matrix algebra</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title"><b>Sections</b></h2>
   
  <ul>
  <li><a href="#time-series-anomaly-detection-paradigms" id="toc-time-series-anomaly-detection-paradigms" class="nav-link active" data-scroll-target="#time-series-anomaly-detection-paradigms"><span class="header-section-number">9.1</span> Time series anomaly detection paradigms</a></li>
  <li><a href="#weird-times" id="toc-weird-times" class="nav-link" data-scroll-target="#weird-times"><span class="header-section-number">9.2</span> Weird times</a>
  <ul class="collapse">
  <li><a href="#hampel-identifier" id="toc-hampel-identifier" class="nav-link" data-scroll-target="#hampel-identifier">Hampel identifier</a></li>
  <li><a href="#surprisal-anomalies" id="toc-surprisal-anomalies" class="nav-link" data-scroll-target="#surprisal-anomalies">Surprisal anomalies</a></li>
  <li><a href="#multivariate-time-series" id="toc-multivariate-time-series" class="nav-link" data-scroll-target="#multivariate-time-series">Multivariate time series</a></li>
  </ul></li>
  <li><a href="#weird-series" id="toc-weird-series" class="nav-link" data-scroll-target="#weird-series"><span class="header-section-number">9.3</span> Weird series</a></li>
  <li><a href="#surveillance" id="toc-surveillance" class="nav-link" data-scroll-target="#surveillance"><span class="header-section-number">9.4</span> Surveillance</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-27933797-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-27933797-2');
  gtag('config', 'G-JKBLG3XQGY')
</script>
<link href="https://fonts.googleapis.com/css?family=Fira+Sans|Noto+Serif" rel="stylesheet">
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/hack-font@3/build/web/hack-subset.css">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-noneuclidean" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Time series data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>For this chapter, we will load some additional packages designed to work with time series data. To learn more about these packages and their use in time series analysis, see <span class="citation" data-cites="fpp3">Hyndman and Athanasopoulos (<a href="references.html#ref-fpp3" role="doc-biblioref">2021</a>)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tsibble)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fable)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(feasts)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tsibbledata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="time-series-anomaly-detection-paradigms" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="time-series-anomaly-detection-paradigms"><span class="header-section-number">9.1</span> Time series anomaly detection paradigms</h2>
<p>Time series data are observations that are collected over time. In this book, we will only consider time series that are observed at regular intervals, such as annually, monthly, or hourly.</p>
<p>When considering time series data, we can distinguish between three different anomaly detection paradigms:</p>
<ol type="1">
<li><strong>Weird times</strong>: Identifying anomalies within a time series in historical data.</li>
<li><strong>Weird series</strong>: Identifying an anomalous time series within a collection of time series.</li>
<li><strong>Surveillance</strong>: Identifying anomalies within a time series in real time</li>
</ol>
<p>These can be illustrated using the following examples.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-tsparadigms" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tsparadigms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-tsparadigms-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tsparadigms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: The three main anomaly detection paradigms. In the top panel, we aim to identify unusual observations within historical data. In the middle panel, we aim to identify an unusual time series within a collection of time series. In the bottom panel, we aim to identify an unusual observation in the most recent time period.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Weird times</strong>: In the top plot, we are looking for historical anomalies within time series data. This is common in quality control, or in data cleaning. The aim is to find time periods where the observations are different from the rest of the data. Again, it can easily be extended to multivariate time series, where we look for time periods when one or more of the series may display unusual observations.</p>
<p><strong>Weird series</strong>: In the middle plot, we are looking for an anomalous time series within a collection of time series. The observations within each series may all be consistent, but the series as a whole may be unusual. This is, by its nature, a multivariate problem. It is common in finance, where we look for unusual behaviour of a stock within a collection of stocks, or in health, where we look for unusual behaviour of a patient within a collection of patients.</p>
<p><strong>Surveillance</strong>: In the bottom plot, we are looking for an anomaly in the next observation in the time series. This is commonly done in surveillance, when a time series is monitored in real time to identify an unusual observation, and appropriate action taken. An anomaly in this context, is an observation that is very different from what was forecast. Although only a single time series is shown in this plot, the idea easily extends to multivariate time series, where we look for something unusual occurring in the next time period across a set of time series.</p>
<p>We will discuss each of these paradigms in turn.</p>
</section>
<section id="weird-times" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="weird-times"><span class="header-section-number">9.2</span> Weird times</h2>
<p>As a vehicle of illustration, we will consider French mortality rates, disaggregated by age and sex. These are obtained from the <span class="citation" data-cites="HMD">Human Mortality Database (<a href="references.html#ref-HMD" role="doc-biblioref">2024</a>)</span>. We will consider male and female data from 1816 to 1999 over ages 0 to 85, giving 172 separate time series, each of length 184. In fact, the top plot in <a href="#fig-tsparadigms" class="quarto-xref">Figure&nbsp;<span>9.1</span></a> shows the male mortality rates for 25 year olds over this time period.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fr_mortality</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 31,648 × 4
#&gt;     Year   Age Sex    Mortality
#&gt;    &lt;int&gt; &lt;int&gt; &lt;chr&gt;      &lt;dbl&gt;
#&gt;  1  1816     0 Female   0.187  
#&gt;  2  1816     1 Female   0.0467 
#&gt;  3  1816     2 Female   0.0339 
#&gt;  4  1816     3 Female   0.0229 
#&gt;  5  1816     4 Female   0.0160 
#&gt;  6  1816     5 Female   0.0138 
#&gt;  7  1816     6 Female   0.0121 
#&gt;  8  1816     7 Female   0.0104 
#&gt;  9  1816     8 Female   0.00891
#&gt; 10  1816     9 Female   0.00760
#&gt; # ℹ 31,638 more rows</code></pre>
</div>
</div>
<p><a href="#fig-fr_mortality_time_plots" class="quarto-xref">Figure&nbsp;<span>9.2</span></a> shows the data for both sexes and all ages. The mortality rates have improved over time for all ages, especially since 1950. Infant mortality (age 0) is much higher than the rest of childhood, with mortality rates at a minimum at about age 10 in all years. The highest mortality rates are for the oldest age groups. The effect of the two wars are particularly evident in the male mortality rates.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fr_mortality <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Mortality, <span class="at">color =</span> Age, <span class="at">group =</span> Age)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> Sex) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-fr_mortality_time_plots" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fr_mortality_time_plots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-fr_mortality_time_plots-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fr_mortality_time_plots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: French mortality rates by sex and age from 1816 to 1999. We use a log scale because the rates are vastly different for different age groups.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Anomaly detection methods for identifying weird time anomalies are usually based on fitting a smooth function <span class="math inline">m_t</span> through the observations, estimating the spread in the series <span class="math inline">a_t</span>, and computing the standardized residuals <span class="math inline">e_t = (y_t - m_t)/a_t</span>. We then identify anomalies in the <span class="math inline">e_t</span> series using one of the methods discussed in <a href="06-density.html" class="quarto-xref"><span>Chapter 6</span></a> or <a href="07-distance.html" class="quarto-xref"><span>Chapter 7</span></a>. To illustrate, we will consider two such approaches, but many more are possible depending on how <span class="math inline">m_t</span> and <span class="math inline">a_t</span> are estimated, and how anomalies are identified in <span class="math inline">e_t</span>.</p>
<section id="hampel-identifier" class="level3">
<h3 class="anchored" data-anchor-id="hampel-identifier">Hampel identifier</h3>
<p>The Hampel identifier is due to a proposal of Frank Hampel <span class="citation" data-cites="Davies1993">(<a href="references.html#ref-Davies1993" role="doc-biblioref">Davies and Gather 1993</a>)</span>, and is designed to identify anomalies in a time series based on whether an observation is very different from the neighbouring observations. Suppose we define neighbourhoods comprising observations within <span class="math inline">h</span> time periods. Then the local median is given by <span class="math display">
m_t = \text{median}(y_{t-h}, \dots, y_{t+h}).
</span> This is also called a “moving median”, a “running median” or a “rolling median”. Similarly, the local median absolute deviation (MAD) is given by <span class="math display">
a_t = \text{median}(|y_{t-h}-m_t|, \dots, |y_{t+h}- m_t|).
</span> This measures the variation of the series in the neighbourhood of time <span class="math inline">t</span>. The residuals <span class="math inline">e_t = (y_t-m_t)/a_t</span> provide a measure for how different an observation <span class="math inline">y_t</span> is from its neighbours. The Hampel identifier denotes an observation as an anomaly if <span class="math display">|e_t| &gt; \tau</span> for some threshold <span class="math inline">\tau</span>. A related idea is the Hampel filter, where each anomaly is replaced by the local median <span class="math inline">m_t</span>.</p>
<p>The threshold is often set under the assumption of a Normal distribution, for which the MAD is equal to 0.67445 times the standard deviation. So it is common to set <span class="math inline">\tau = k/0.67445</span> where <span class="math inline">k</span> is the number of standard deviations permitted before an observation is considered an outlier. Because we apply the rule repeatedly over the length of a time series, we need to be careful of the problem of multiple comparisons, where the probability of a false positive overall is much larger than the probability of a false positive for each individual test. However, it is not straightforward to adjust the probabilities because the tests are not independent, and the dependency between them depends on the window size <span class="math inline">h</span>, and the characteristics of the time series. Setting <span class="math inline">k=5</span> or 6 seems to work quite well for many problems.</p>
<p>The <code>hampel_anomalies()</code> function implements this algorithm. The code below applies the algorithm to all 172 time series in <code>fr_mortality</code>. The <code>bandwidth</code> argument corresponds to <span class="math inline">h</span>, and the <code>k</code> argument corresponds to <span class="math inline">k</span> above.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fr_anomalies <span class="ot">&lt;-</span> fr_mortality <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age, Sex) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hampel =</span> <span class="fu">hampel_anomalies</span>(Mortality, <span class="at">bandwidth =</span> <span class="dv">7</span>, <span class="at">k =</span> <span class="dv">6</span>)) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(hampel) <span class="sc">|&gt;</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Year, Age)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>fr_anomalies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 403 × 5
#&gt;     Year   Age Sex    Mortality hampel
#&gt;    &lt;int&gt; &lt;int&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;lgl&gt; 
#&gt;  1  1832    18 Male     0.00868 TRUE  
#&gt;  2  1832    30 Female   0.0127  TRUE  
#&gt;  3  1832    30 Male     0.0123  TRUE  
#&gt;  4  1832    31 Female   0.0130  TRUE  
#&gt;  5  1832    31 Male     0.0126  TRUE  
#&gt;  6  1832    33 Female   0.0135  TRUE  
#&gt;  7  1832    39 Female   0.0159  TRUE  
#&gt;  8  1832    40 Female   0.0167  TRUE  
#&gt;  9  1832    41 Female   0.0171  TRUE  
#&gt; 10  1832    41 Male     0.0151  TRUE  
#&gt; # ℹ 393 more rows</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find years containing anomalies</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>yrs <span class="ot">&lt;-</span> fr_anomalies <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Year, Sex) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>fr_anomalies_plot_male2 <span class="ot">&lt;-</span> fr_anomalies <span class="sc">|&gt;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"Male"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Age)) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> Sex) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1820</span>, <span class="dv">2000</span>, <span class="at">by =</span> <span class="dv">20</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">range</span>(yrs<span class="sc">$</span>Year)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> <span class="fu">unique</span>(yrs<span class="sc">$</span>Year[yrs<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">"Male"</span>]),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"grey"</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col =</span> <span class="st">"#478cb2"</span>) <span class="sc">+</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> yrs <span class="sc">|&gt;</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"Male"</span>, <span class="sc">!</span>Year <span class="sc">%in%</span> <span class="dv">1915</span><span class="sc">:</span><span class="dv">1918</span>),</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="dv">75</span>, <span class="at">label =</span> Year), <span class="at">col =</span> <span class="st">"#478cb2"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">seed =</span> <span class="dv">1967</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">4</span>, <span class="dv">85</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>fr_anomalies_plot_female2 <span class="ot">&lt;-</span> fr_anomalies <span class="sc">|&gt;</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"Female"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Age)) <span class="sc">+</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> Sex) <span class="sc">+</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1820</span>, <span class="dv">2000</span>, <span class="at">by =</span> <span class="dv">20</span>),</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">range</span>(yrs<span class="sc">$</span>Year)</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> <span class="fu">unique</span>(yrs<span class="sc">$</span>Year[yrs<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">"Female"</span>]),</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"grey"</span></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"French mortality anomalies"</span>) <span class="sc">+</span></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col =</span> <span class="st">"#c1653a"</span>) <span class="sc">+</span></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>  ggrepel<span class="sc">::</span><span class="fu">geom_text_repel</span>(</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> yrs[yrs<span class="sc">$</span>Sex <span class="sc">==</span> <span class="st">"Female"</span>, ],</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="dv">75</span>, <span class="at">label =</span> Year), <span class="at">col =</span> <span class="st">"#c1653a"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">seed =</span> <span class="dv">1967</span></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">4</span>, <span class="dv">85</span>)</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>patchwork<span class="sc">::</span><span class="fu">wrap_plots</span>(</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>  fr_anomalies_plot_female2,</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>  fr_anomalies_plot_male2,</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">1</span></span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-hampel_fr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hampel_fr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-hampel_fr-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hampel_fr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: French mortality observations identified as anomalies using the Hampel identifier.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-hampel_fr" class="quarto-xref">Figure&nbsp;<span>9.3</span></a> shows the 403 observations (out of 31648) that have been identified as anomalies, showing the wars and epidemics that have occurred over time. The following events in French history are evident in the data:</p>
<ul>
<li>1832, 1849, 1854: Cholera outbreaks</li>
<li>1853-1856: Crimean war</li>
<li>1870: Franco-Prussian war</li>
<li>1871: Repression of the ‘Commune de Paris’</li>
<li>1914-1918: World War I</li>
<li>1918: Spanish flu outbreak</li>
<li>1940-1944: World War II</li>
</ul>
</section>
<section id="surprisal-anomalies" class="level3">
<h3 class="anchored" data-anchor-id="surprisal-anomalies">Surprisal anomalies</h3>
<p>The Hampel identifier worked well for the annual mortality series, but the local median approach will break down when there is seasonality or other systematic patterns in the data. However, the same idea can be adapted by replacing the local median with a more sophisticated way of modelling the signal in the data. One such method is STL (Seasonal Trend decomposition using Loess) due to <span class="citation" data-cites="Cleveland1990">Cleveland et al. (<a href="references.html#ref-Cleveland1990" role="doc-biblioref">1990</a>)</span>, and extended by <span class="citation" data-cites="mstl">Bandara, Hyndman, and Bergmeir (<a href="references.html#ref-mstl" role="doc-biblioref">2022</a>)</span> to handle multiple seasonal periods or series with no seasonality.</p>
<p>We will apply this idea to find unusual observations in US weekly mortality data between 2015 and 2024, obtained from the <span class="citation" data-cites="HMD">Human Mortality Database (<a href="references.html#ref-HMD" role="doc-biblioref">2024</a>)</span>. The following code downloads the data from the website, and wrangles it into a <code>tsibble</code> object (a special type of tibble designed for time series data).</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>us_stmf <span class="ot">&lt;-</span> <span class="st">"https://www.mortality.org/File/GetDocument/Public/STMF/Outputs/USAstmfout.csv"</span> <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">read.csv</span>(<span class="at">header =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create time index varaible</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Week =</span> <span class="fu">yearweek</span>(<span class="fu">paste0</span>(Year,<span class="st">"-W"</span>,Week))) <span class="sc">|&gt;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Consider only sexes combined, and omit last week due to reporting delays</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">"b"</span>, Week <span class="sc">&lt;</span> <span class="fu">max</span>(Week) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Fix column names</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Week, <span class="st">`</span><span class="at">X0.14.1</span><span class="st">`</span><span class="sc">:</span><span class="st">`</span><span class="at">X85..1</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"0-14"</span> <span class="ot">=</span> <span class="st">`</span><span class="at">X0.14.1</span><span class="st">`</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"15-64"</span> <span class="ot">=</span> <span class="st">`</span><span class="at">X15.64.1</span><span class="st">`</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"65-74"</span> <span class="ot">=</span> <span class="st">`</span><span class="at">X65.74.1</span><span class="st">`</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"75-84"</span> <span class="ot">=</span> <span class="st">`</span><span class="at">X75.84.1</span><span class="st">`</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"85+"</span> <span class="ot">=</span> <span class="st">`</span><span class="at">X85..1</span><span class="st">`</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a tsibble object</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="sc">-</span>Week, <span class="at">names_to =</span> <span class="st">"Age group"</span>, <span class="at">values_to =</span> <span class="st">"Mortality"</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tsibble</span>(<span class="at">index =</span> Week, <span class="at">key =</span> <span class="st">`</span><span class="at">Age group</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><a href="#fig-stmf" class="quarto-xref">Figure&nbsp;<span>9.4</span></a> shows the data on five age groups. There appears to be no seasonality in the 0–14 age group, but all other age groups have seasonal peaks around the start of January each year due to winter illnesses, with the seasonal strength increasing with age. There is a noticeable change in mortality rates during 2020, 2021 and the start of 2022. This is due to COVID-19.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>us_stmf <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(Mortality) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="st">`</span><span class="at">Age group</span><span class="st">`</span> <span class="sc">~</span> ., <span class="at">scales =</span> <span class="st">"free_y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-stmf" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stmf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-stmf-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stmf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.4: Weekly mortality rates for different age groups in the United States between 2015 and 2024.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Next, we apply an STL model to the mortality rates in each age group. This helps separate out the regular seasonality, from any unusual fluctuations.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>stmf_fit <span class="ot">&lt;-</span> us_stmf <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">stl =</span> <span class="fu">STL</span>(Mortality)) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>.model, <span class="sc">-</span>.innov)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>stmf_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 2,530 × 5
#&gt;    `Age group`     Week Mortality  .fitted      .resid
#&gt;    &lt;chr&gt;         &lt;week&gt;     &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;
#&gt;  1 0-14        2015 W02  0.000521 0.000534 -0.0000130 
#&gt;  2 0-14        2015 W03  0.000536 0.000526  0.0000100 
#&gt;  3 0-14        2015 W04  0.000530 0.000526  0.00000406
#&gt;  4 0-14        2015 W05  0.000525 0.000530 -0.00000532
#&gt;  5 0-14        2015 W06  0.000493 0.000526 -0.0000327 
#&gt;  6 0-14        2015 W07  0.000527 0.000537 -0.0000100 
#&gt;  7 0-14        2015 W08  0.000529 0.000539 -0.00000961
#&gt;  8 0-14        2015 W09  0.000521 0.000525 -0.00000366
#&gt;  9 0-14        2015 W10  0.000502 0.000538 -0.0000357 
#&gt; 10 0-14        2015 W11  0.000505 0.000533 -0.0000279 
#&gt; # ℹ 2,520 more rows</code></pre>
</div>
</div>
<p>The <code>.fitted</code> column contains <span class="math inline">m_t</span>, and the <code>.resid</code> column contains estimates of <span class="math inline">y_t - m_t</span>, where <span class="math inline">m_t</span> takes account of any seasonality in the data. We will estimate the spread <span class="math inline">a_t</span> using a multiple of the IQR, where the multiple is chosen so that <span class="math inline">a_t</span> is equivalent to a standard deviation if the data were normally distributed. A separate estimate of spread is needed for each age group because the mortality rates are so different.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>stmf_scores <span class="ot">&lt;-</span> stmf_fit <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="st">`</span><span class="at">Age group</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">s =</span> <span class="fu">IQR</span>(.resid),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">e =</span> .resid <span class="sc">/</span> <span class="fu">IQR</span>(.resid) <span class="sc">/</span> <span class="fl">1.349</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>stmf_scores</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 2,530 × 7
#&gt;    `Age group`     Week Mortality  .fitted      .resid         s       e
#&gt;    &lt;chr&gt;         &lt;week&gt;     &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
#&gt;  1 0-14        2015 W02  0.000521 0.000534 -0.0000130  0.0000273 -0.354 
#&gt;  2 0-14        2015 W03  0.000536 0.000526  0.0000100  0.0000273  0.272 
#&gt;  3 0-14        2015 W04  0.000530 0.000526  0.00000406 0.0000273  0.110 
#&gt;  4 0-14        2015 W05  0.000525 0.000530 -0.00000532 0.0000273 -0.145 
#&gt;  5 0-14        2015 W06  0.000493 0.000526 -0.0000327  0.0000273 -0.887 
#&gt;  6 0-14        2015 W07  0.000527 0.000537 -0.0000100  0.0000273 -0.273 
#&gt;  7 0-14        2015 W08  0.000529 0.000539 -0.00000961 0.0000273 -0.261 
#&gt;  8 0-14        2015 W09  0.000521 0.000525 -0.00000366 0.0000273 -0.0994
#&gt;  9 0-14        2015 W10  0.000502 0.000538 -0.0000357  0.0000273 -0.969 
#&gt; 10 0-14        2015 W11  0.000505 0.000533 -0.0000279  0.0000273 -0.758 
#&gt; # ℹ 2,520 more rows</code></pre>
</div>
</div>
<p>At this point, we could identify a point as an anomaly if <span class="math inline">|e_t|</span> is greater than some threshold, as was done with the Hampel identifier. But we will use surprisals with probabilities calculated using a GPD, as it is a safer calculation making fewer assumptions about the distribution of the residuals.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>stmf_scores <span class="ot">&lt;-</span> stmf_scores <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="fu">surprisals</span>(e, <span class="at">distribution =</span> <span class="fu">dist_normal</span>(), <span class="at">approximation =</span> <span class="st">"gpd"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(prob <span class="sc">&lt;</span> <span class="fl">0.02</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>stmf_scores <span class="sc">|&gt;</span> <span class="fu">arrange</span>(prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 56 × 8
#&gt;    `Age group`     Week Mortality .fitted   .resid        s     e    prob
#&gt;    &lt;chr&gt;         &lt;week&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
#&gt;  1 85+         2020 W16   0.210   0.161   0.0492   0.00614   5.94 0.00167
#&gt;  2 75-84       2020 W15   0.0633  0.0494  0.0139   0.00181   5.70 0.00196
#&gt;  3 85+         2020 W15   0.208   0.162   0.0464   0.00614   5.60 0.00211
#&gt;  4 75-84       2020 W16   0.0616  0.0485  0.0131   0.00181   5.37 0.00249
#&gt;  5 65-74       2020 W15   0.0253  0.0199  0.00537  0.000755  5.27 0.00265
#&gt;  6 15-64       2021 W36   0.00541 0.00440 0.00101  0.000143  5.23 0.00273
#&gt;  7 85+         2020 W17   0.201   0.158   0.0427   0.00614   5.15 0.00290
#&gt;  8 15-64       2021 W35   0.00536 0.00440 0.000958 0.000143  4.95 0.00338
#&gt;  9 15-64       2021 W37   0.00526 0.00433 0.000930 0.000143  4.81 0.00378
#&gt; 10 75-84       2020 W53   0.0714  0.0597  0.0117   0.00181   4.79 0.00383
#&gt; # ℹ 46 more rows</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>us_stmf <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(Mortality) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="st">`</span><span class="at">Age group</span><span class="st">`</span> <span class="sc">~</span> ., <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> stmf_scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-stl_anomalies" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stl_anomalies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-stl_anomalies-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stl_anomalies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.5: US weekly mortality rates identified as anomalies using surprisal probabilities obtained from applying STL to each series, computing the surprisals from the standardized residuals, and using a GPD on the surprisals.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A total of 56 observations have surprisal probabilities less than 0.02, with the most extreme being in weeks 15–16 of 2020, in the elderly age groups. Although the test can pick up unusually low or unusually high mortality rates, only 2 of the 56 identified anomalies is for low mortality, and that is for 85+ year olds in Week 3 of 2020 and in Week 15 of 2021. In both weeks, it is possible that the elderly were taking precautions against COVID-19, resulting in restricted movements, and therefore lower mortality rates.</p>
<p>There are four anomalous peaks in the plot, centred on the following dates:</p>
<ul>
<li>2020 W14 – W18</li>
<li>2020 W49 – 2021 W03</li>
<li>2021 W33 – W39</li>
<li>2022 W02 – W05</li>
</ul>
<p>Some of these periods affected some age groups more than others.</p>
</section>
<section id="multivariate-time-series" class="level3">
<h3 class="anchored" data-anchor-id="multivariate-time-series">Multivariate time series</h3>
<p>The above analysis treats each series separately, and seeks to find anomalies within each series, regardless of the behaviour of related series. To take account of all series simultaneously, we need to take a multivariate approach, where we are looking for time periods that are anomalous across multiple series. One way to do this is to first take principal components of the series, and then apply the preceding procedure to the series of first principal component scores.</p>
<p>First we convert the series to logs as they are on vastly different scales, then we transform the data to wide form. Finally, we compute the first principal component of the resulting matrix.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to wide form</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>us_wide <span class="ot">&lt;-</span> us_stmf <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">logm =</span> <span class="fu">log</span>(Mortality)) <span class="sc">|&gt;</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> Week, <span class="at">names_from =</span> <span class="st">`</span><span class="at">Age group</span><span class="st">`</span>, <span class="at">values_from =</span> logm)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute 1 principal component from mortality rates</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>pcs <span class="ot">&lt;-</span> us_wide <span class="sc">|&gt;</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Week) <span class="sc">|&gt;</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prcomp</span>(<span class="at">rank =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">augment</span>(us_wide <span class="sc">|&gt;</span> <span class="fu">select</span>(Week))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The resulting series is plotted in <a href="#fig-us_stmf_pcs" class="quarto-xref">Figure&nbsp;<span>9.6</span></a>, and shows strong seasonality, along with large peaks during the periods of COVID outbreaks. Now we can apply an STL model to find anomalies in this series. There is no need to scale the residuals because there is only one series.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>pc_anomalies <span class="ot">&lt;-</span> pcs <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tsibble</span>(<span class="at">index =</span> Week) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">stl =</span> <span class="fu">STL</span>(.fittedPC1)) <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">|&gt;</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>.model, <span class="sc">-</span>.innov) <span class="sc">|&gt;</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="fu">surprisals</span>(.resid, <span class="at">distribution =</span> <span class="fu">dist_normal</span>(), <span class="at">approximation =</span> <span class="st">"gpd"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(prob <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>pc_anomalies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tsibble: 25 x 5 [1W]
#&gt;        Week .fittedPC1 .fitted .resid     prob
#&gt;      &lt;week&gt;      &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
#&gt;  1 2020 W03     0.0346  0.284  -0.250 0.0355  
#&gt;  2 2020 W04     0.0314  0.258  -0.227 0.0477  
#&gt;  3 2020 W14     0.458   0.119   0.338 0.00861 
#&gt;  4 2020 W15     0.623   0.152   0.471 0.000468
#&gt;  5 2020 W16     0.570   0.122   0.448 0.000829
#&gt;  6 2020 W17     0.479   0.101   0.377 0.00402 
#&gt;  7 2020 W18     0.367   0.0894  0.277 0.0239  
#&gt;  8 2020 W50     0.696   0.432   0.264 0.0290  
#&gt;  9 2020 W51     0.732   0.438   0.294 0.0184  
#&gt; 10 2020 W52     0.768   0.469   0.299 0.0170  
#&gt; # ℹ 15 more rows</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot principal component scores</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>pcs <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Week, <span class="at">y =</span> .fittedPC1)) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"First principal component scores"</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> pc_anomalies, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-us_stmf_pcs" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-us_stmf_pcs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-us_stmf_pcs-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-us_stmf_pcs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.6: The first principal component scores calculated from the weekly US mortality rates, along with the identified anomalies. Compare the individual series shown in <a href="#fig-stmf" class="quarto-xref">Figure&nbsp;<span>9.4</span></a>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As expected, many of the same weeks identified earlier in an analysis of individual series have been returned. The probability of false positives increases with both the length of each series, and the number of each series. So we have used a larger probability threshold here than in the analysis of individual series. Conversely, some anomalies might appear to be marginal in the individual series, but when the series are combined like this, the anomalous periods may be clearer. This appears to be the case in weeks 3 and 4 of 2020, where unusually low mortality rates are seen, probably because of restricted movements due to growing uncertainty associated with the spread of COVID-19. (The earlier analysis only showed an anomaly in this period for 85+ year olds in 2020 W3.) Unusually low mortality rates have also been identified in Weeks 13 and 15 of 2021, probably also due to restricted movements, especially of older people.</p>
</section>
</section>
<section id="weird-series" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="weird-series"><span class="header-section-number">9.3</span> Weird series</h2>
<p>Next we consider unusual series within a large collection of time series.</p>
<p>To illustrate the ideas we will use a data set of monthly observations on the Australian Pharmaceutical Benefits Scheme (PBS), from July 1991 to June 2008. The PBS involves the Australian government subsidising certain pharmaceutical products, to allow more equitable access to essential medicines. The data set contains monthly sales volumes of those products being subsidised, classified according to the Anatomical Therapeutic Chemical (ATC) classification system, by the type of government subsidy, and by whether the purchaser was in a concession group (such as pensioner, unemployed, etc.). There are 336 separate time series contained in the <code>PBS</code> data set.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute features</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>PBS_feat <span class="ot">&lt;-</span> PBS <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">features</span>(Scripts, <span class="fu">feature_set</span>(<span class="at">pkgs =</span> <span class="st">"feasts"</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep series with no missing features</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>PBS_feat_nomissing <span class="ot">&lt;-</span> PBS_feat <span class="sc">|&gt;</span> <span class="fu">na.omit</span>()</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute principal components</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>PBS_prcomp <span class="ot">&lt;-</span> PBS_feat_nomissing <span class="sc">|&gt;</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Concession, <span class="sc">-</span>Type, <span class="sc">-</span>ATC1, <span class="sc">-</span>ATC2) <span class="sc">|&gt;</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prcomp</span>(<span class="at">scale =</span> <span class="cn">TRUE</span>, <span class="at">rank =</span> <span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(PBS_feat_nomissing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the first two components</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>PBS_prcomp <span class="sc">|&gt;</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .fittedPC1, <span class="at">y =</span> .fittedPC2)) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Principal component 1"</span>, <span class="at">y =</span> <span class="st">"Principal component 2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-weirdseries_pca" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weirdseries_pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-weirdseries_pca-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weirdseries_pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.7: The first two principal components computed from all features applied to the PBS data. Three series have been omitted as they returned missing features.
</figcaption>
</figure>
</div>
</div>
</div>
<p>There are two series which are clearly separated from the rest, with principal component 2 less than -15. Although it is not necessary here, because these two anomalies are so obvious, we can confirm them using KDE surprisal probabilities.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>PBS_prcomp <span class="ot">&lt;-</span> PBS_prcomp <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="fu">surprisals</span>(PBS_prcomp <span class="sc">|&gt;</span> <span class="fu">select</span>(.fittedPC1,.fittedPC2), <span class="at">loo =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Concession, Type, ATC2, .fittedPC1, .fittedPC2, prob) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(prob)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>PBS_prcomp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 333 × 6
#&gt;    Concession   Type        ATC2  .fittedPC1 .fittedPC2    prob
#&gt;    &lt;chr&gt;        &lt;chr&gt;       &lt;chr&gt;      &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
#&gt;  1 Concessional Safety net  J06        7.09      -17.9  0      
#&gt;  2 General      Co-payments C05        8.56      -23.1  0      
#&gt;  3 General      Co-payments S02        5.58      -11.6  0.00901
#&gt;  4 General      Co-payments A15       -1.13       -8.90 0.0120 
#&gt;  5 General      Co-payments R06        3.51       -6.25 0.0150 
#&gt;  6 General      Co-payments P03        5.14       -9.73 0.0180 
#&gt;  7 Concessional Co-payments J06        4.46       -9.67 0.0210 
#&gt;  8 General      Safety net  D11        2.60       -3.67 0.0240 
#&gt;  9 General      Co-payments S03       -0.788      -6.33 0.0270 
#&gt; 10 General      Co-payments J06        1.86       -7.44 0.0300 
#&gt; # ℹ 323 more rows</code></pre>
</div>
</div>
<p>Now, let’s plot the two most anomalous series, to see if we can spot what is so unusual about them.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull out most unusual series using the first principal component</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> PBS_prcomp <span class="sc">|&gt;</span> <span class="fu">filter</span>(prob <span class="sc">&lt;</span> <span class="fl">0.001</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualise the unusual series</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>PBS <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(outliers, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Concession"</span>, <span class="st">"Type"</span>, <span class="st">"ATC2"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(Scripts) <span class="sc">+</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="fu">vars</span>(Concession, Type, ATC2), <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Outlying time series in PC space"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-weirdseries_anomalies" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-weirdseries_anomalies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-weirdseries_anomalies-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weirdseries_anomalies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.8: The most unusual series, as determined by the principal component scores.
</figcaption>
</figure>
</div>
</div>
</div>
<p>These series both contain almost all zeros, with just a few non-zero values. The three series we omitted may also be unusual, so let’s plot them as well.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>missing <span class="ot">&lt;-</span> PBS_feat <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(PBS_feat_nomissing) <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ATC2, Type, Concession)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualise the series with missing features</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>PBS <span class="sc">|&gt;</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">semi_join</span>(missing, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Concession"</span>, <span class="st">"Type"</span>, <span class="st">"ATC2"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(Scripts) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="fu">vars</span>(Concession, Type, ATC2), <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Time series with missing features"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-pbs_missing" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pbs_missing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-pbs_missing-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pbs_missing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.9: The series for which some features were missing.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Similarly, one of these series contains only zeros apart from in one month. The other two contain only zeros for the period when observations were recorded.</p>
</section>
<section id="surveillance" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="surveillance"><span class="header-section-number">9.4</span> Surveillance</h2>
<p>In surveillance, we are interested in identifying anomalies in real time, either within one series or across several time series. This is common in monitoring systems, where we want to identify unusual behaviour as soon as it occurs. For example, in a manufacturing plant, we may want to identify when a machine is not operating as expected, and take action to prevent further problems. In retail, we may want to identify when sales are unusually high or low, and adjust stock levels if necessary.</p>
<p>Again, we will use the PBS data. For this example, we will combine the data into the ATC level 2 groups, and look at total sales volumes (measured in thousands of scripts). The resulting data set contains 84 separate time series, one for each <code>ATC2</code> value.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>pbs <span class="ot">&lt;-</span> PBS <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(ATC2, Month) <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ATC2) <span class="sc">|&gt;</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Scripts =</span> <span class="fu">sum</span>(Scripts) <span class="sc">/</span> <span class="fl">1e3</span>, <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">t =</span> <span class="fu">as.numeric</span>(Month <span class="sc">-</span> <span class="fu">min</span>(Month) <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>pbs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tsibble: 17,016 x 4 [1M]
#&gt; # Key:       ATC2 [84]
#&gt;    ATC2     Month Scripts     t
#&gt;    &lt;chr&gt;    &lt;mth&gt;   &lt;dbl&gt; &lt;dbl&gt;
#&gt;  1 A01   1991 Jul    22.6     1
#&gt;  2 A01   1991 Aug    20.4     2
#&gt;  3 A01   1991 Sep    21.4     3
#&gt;  4 A01   1991 Oct    23.7     4
#&gt;  5 A01   1991 Nov    23.5     5
#&gt;  6 A01   1991 Dec    26.3     6
#&gt;  7 A01   1992 Jan    22.0     7
#&gt;  8 A01   1992 Feb    16.4     8
#&gt;  9 A01   1992 Mar    17.2     9
#&gt; 10 A01   1992 Apr    18.8    10
#&gt; # ℹ 17,006 more rows</code></pre>
</div>
</div>
<p>Let’s first look at the time series for just one ATC group: A12 (Mineral supplements). In fact, this is the same series as was shown in the top panel of <a href="#fig-tsparadigms" class="quarto-xref">Figure&nbsp;<span>9.1</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>pbs <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ATC2 <span class="sc">==</span> <span class="st">"A12"</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(Scripts) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scripts for ATC group A12 (Mineral supplements)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-a12" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-a12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-a12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-a12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.10: The monthly script volume for mineral supplements (ATC group A12) on the Australian PBS.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Here there has been a sudden drop in sales at the end of 2005, most likely because of some products no longer being eligible for subsidy. There can also be sudden jumps in sales when a new product becomes available, or a new class of drugs is added to the scheme.</p>
<p>The goal of surveillance is to identify these anomalies as soon as they occur. We can do this by fitting a model to the data, and then comparing the observed values to the model’s forecasts. If the observed values are very different from the forecast, then we have an anomaly.</p>
<p>Statistical forecasting models provide forecasts in the form of probability distributions. Let <span class="math inline">y_t</span> denote the observation of a time series at time <span class="math inline">t</span>. Then a forecast can be expressed as a conditional distribution <span class="math display">
  f(y_{t+h} | y_1, \dots, y_{t}, \bm{x}_t),
</span> where <span class="math inline">y_1,\dots,y_t</span> denotes the observed history of the series, and <span class="math inline">\bm{x}_t</span> contains any other information available at time <span class="math inline">t</span> that is used in the model. The forecast “horizon” is given by <span class="math inline">h</span>, denoting the number of time periods into the future that we wish to forecast. Different forecasting methods use different conditioning information, and result in a different form of the forecast distribution. See <span class="citation" data-cites="fpp3">Hyndman and Athanasopoulos (<a href="references.html#ref-fpp3" role="doc-biblioref">2021</a>)</span> for a detailed discussion of forecasting methods.</p>
<p>Once we observe the value of <span class="math inline">y_{t+h}</span>, we can calculate the corresponding surprisal probability in the same way as we discussed in <a href="06-density.html#sec-surprisal-probabilities" class="quarto-xref"><span>Section 6.2</span></a>. Because we are interested in real-time surveillance, we need only consider the one-step-ahead forecast density, <span class="math inline">f(y_{t+1} | y_1, \dots, y_{t})</span>. We can then calculate the surprisal as <span class="math display">
  s_{t+1} = -\log f(y_{t+1} | y_1, \dots, y_{t}, \bm{x}_t).
</span> This needs to be done iteratively for each time period, updating the model as new data becomes available. Since we need some observations with which to fit a model, we can’t begin the process at time <span class="math inline">t=1</span>. Instead, we’ll begin at time <span class="math inline">t=I</span>, where <span class="math inline">I</span> is the smallest number of observations with which we can reasonably estimate the time series model. The value of <span class="math inline">I</span> will depend on the complexity of the model being used. For simple models with few parameters, we may be able to set <span class="math inline">I</span> to around 20, but for complex models with many parameters, <span class="math inline">I</span> may need to be much larger.</p>
<p>We can summarise the anomaly detection algorithm for surveillance as follows. First, we’ll change the notation slightly to allow for more than one series. Let <span class="math inline">y_{i,t}</span> denote the observation of the <span class="math inline">i</span>th series at time <span class="math inline">t</span>.</p>
<p>For each <span class="math inline">t = I,I+1,\dots</span>, and for all series <span class="math inline">i=1,\dots,m</span>:</p>
<ul>
<li>Fit a time series model to the series <span class="math inline">y_{i,1},\dots,y_{i,t}</span>, and estimate the one-step forecast density, <span class="math inline">f_{i,t+1}(y \mid y_{i,1},\dots,y_{i,t}, \bm{x}_t)</span>.</li>
<li>Compute the surprisal: <span class="math inline">s_{i,t+1} = -\log f_{i,t+1}(y_{i,t+1}\mid y_{i,1},\dots,y_{i,t}, \bm{x}_t)</span>, and the the surprisal probabilities: <span class="math inline">P(S &gt; s_{i,t+1})</span>.</li>
</ul>
<p>To illustrate, let’s apply this to the <code>pbs</code> data. Starting with <span class="math inline">I=36</span> (3 years of data), we will fit ETS models to all available series <span class="citation" data-cites="fpp3">(Ch 8, <a href="references.html#ref-fpp3" role="doc-biblioref">Hyndman and Athanasopoulos 2021</a>)</span>, and forecast one step ahead in each case. Then we repeat the exercise using 37 observations, then 38 observations, and so on. This is known as a “rolling origin forecast” because the forecast rolls forward by one period each iteration. The process can be illustrated as in <a href="#fig-tscvplots" class="quarto-xref">Figure&nbsp;<span>9.11</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-tscvplots" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tscvplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="09-timeseries_files/figure-html/fig-tscvplots-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tscvplots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.11: Rolling origin forecasts, with the training sets expanding by one observation at each iteration, and one-step forecasts computed for each training set.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Let’s step through the process for the first iteration, with <span class="math inline">t=36</span>. We fit ETS models to each of the time series, with the specific ETS model selected according to the characteristics of the series. See <span class="citation" data-cites="fpp3">(Ch8, <a href="references.html#ref-fpp3" role="doc-biblioref">Hyndman and Athanasopoulos 2021</a>)</span> for details of how this is done.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>pbs_fit <span class="ot">&lt;-</span> pbs <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(t <span class="sc">&lt;=</span> <span class="dv">36</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">ets =</span> <span class="fu">ETS</span>(Scripts))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>pbs_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A mable: 83 x 2
#&gt; # Key:     ATC2 [83]
#&gt;    ATC2           ets
#&gt;    &lt;chr&gt;      &lt;model&gt;
#&gt;  1 A01   &lt;ETS(M,N,A)&gt;
#&gt;  2 A02   &lt;ETS(M,A,M)&gt;
#&gt;  3 A03   &lt;ETS(M,A,M)&gt;
#&gt;  4 A04   &lt;ETS(M,N,A)&gt;
#&gt;  5 A06   &lt;ETS(M,A,M)&gt;
#&gt;  6 A07   &lt;ETS(M,N,M)&gt;
#&gt;  7 A09   &lt;ETS(M,A,M)&gt;
#&gt;  8 A10   &lt;ETS(M,A,M)&gt;
#&gt;  9 A11   &lt;ETS(M,A,M)&gt;
#&gt; 10 A12   &lt;ETS(M,N,A)&gt;
#&gt; # ℹ 73 more rows</code></pre>
</div>
</div>
<p>Forecasts are produced from all fitted models by applying the <code>forecast()</code> function to the model table.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>pbs_fc <span class="ot">&lt;-</span> <span class="fu">forecast</span>(pbs_fit, <span class="at">h =</span> <span class="dv">1</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>pbs_fc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A fable: 83 x 5 [1M]
#&gt; # Key:     ATC2, .model [83]
#&gt;    ATC2  .model    Month       Scripts  .mean
#&gt;    &lt;chr&gt; &lt;chr&gt;     &lt;mth&gt;        &lt;dist&gt;  &lt;dbl&gt;
#&gt;  1 A01   ets    1994 Jul    N(23, 2.1)  23.1 
#&gt;  2 A02   ets    1994 Jul  N(590, 1054) 590.  
#&gt;  3 A03   ets    1994 Jul     N(84, 19)  84.2 
#&gt;  4 A04   ets    1994 Jul     N(69, 15)  69.4 
#&gt;  5 A06   ets    1994 Jul    N(33, 4.2)  33.1 
#&gt;  6 A07   ets    1994 Jul     N(74, 17)  73.6 
#&gt;  7 A09   ets    1994 Jul N(3.7, 0.029)   3.68
#&gt;  8 A10   ets    1994 Jul    N(166, 54) 166.  
#&gt;  9 A11   ets    1994 Jul      N(30, 3)  30.2 
#&gt; 10 A12   ets    1994 Jul    N(100, 23) 100.  
#&gt; # ℹ 73 more rows</code></pre>
</div>
</div>
<p>The forecasts are in the <code>Scripts</code> column. Note that each of them is a Normal distribution where the mean and variance has been estimated using the ETS model. The mean of the forecast distribution is given as <code>.mean</code>.</p>
<p>We can combine these forecasts with the observed values from time <span class="math inline">t=37</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>pbs_compare <span class="ot">&lt;-</span> pbs_fc <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">fcast =</span> Scripts) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(pbs <span class="sc">|&gt;</span> <span class="fu">filter</span>(t <span class="sc">==</span> <span class="dv">37</span>), <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Month"</span>, <span class="st">"ATC2"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Month, ATC2, Scripts, fcast)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>pbs_compare</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tsibble: 83 x 4 [?]
#&gt; # Key:       ATC2 [83]
#&gt;       Month ATC2  Scripts         fcast
#&gt;       &lt;mth&gt; &lt;chr&gt;   &lt;dbl&gt;        &lt;dist&gt;
#&gt;  1 1994 Jul A01     20.9     N(23, 2.1)
#&gt;  2 1994 Jul A02    516.    N(590, 1054)
#&gt;  3 1994 Jul A03     80.5      N(84, 19)
#&gt;  4 1994 Jul A04     66.1      N(69, 15)
#&gt;  5 1994 Jul A06     29.2     N(33, 4.2)
#&gt;  6 1994 Jul A07     68.5      N(74, 17)
#&gt;  7 1994 Jul A09      3.32 N(3.7, 0.029)
#&gt;  8 1994 Jul A10    150.      N(166, 54)
#&gt;  9 1994 Jul A11     27.8       N(30, 3)
#&gt; 10 1994 Jul A12     87.9     N(100, 23)
#&gt; # ℹ 73 more rows</code></pre>
</div>
</div>
<p>Now we can compute the surprisal probabilities from the observed values (column <code>Scripts</code>) and the forecast distributions (column <code>fcast</code>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>pbs_compare <span class="ot">&lt;-</span> pbs_compare <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="fu">surprisals</span>(Scripts, <span class="at">distribution =</span> fcast)) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(prob)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>pbs_compare</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tsibble: 83 x 5 [?]
#&gt; # Key:       ATC2 [83]
#&gt;       Month ATC2  Scripts        fcast    prob
#&gt;       &lt;mth&gt; &lt;chr&gt;   &lt;dbl&gt;       &lt;dist&gt;   &lt;dbl&gt;
#&gt;  1 1994 Jul S01   347.     N(403, 356) 0.00290
#&gt;  2 1994 Jul H02    94.3     N(109, 26) 0.00358
#&gt;  3 1994 Jul S02    63.0      N(74, 16) 0.00465
#&gt;  4 1994 Jul D07   194.     N(222, 101) 0.00580
#&gt;  5 1994 Jul M02    21.6     N(25, 1.9) 0.00686
#&gt;  6 1994 Jul C04     0.248 N(1.2, 0.14) 0.00796
#&gt;  7 1994 Jul V06     6.77  N(7.8, 0.17) 0.00911
#&gt;  8 1994 Jul G01    53.7      N(62, 11) 0.0108 
#&gt;  9 1994 Jul N04    45.3     N(51, 4.4) 0.0117 
#&gt; 10 1994 Jul A12    87.9     N(100, 23) 0.0121 
#&gt; # ℹ 73 more rows</code></pre>
</div>
</div>
<p>The lowest probabilities indicate possible anomalies. Let’s look at the most likely anomaly (or least likely observation), from series S01.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>s01 <span class="ot">&lt;-</span> pbs <span class="sc">|&gt;</span> <span class="fu">filter</span>(ATC2 <span class="sc">==</span> <span class="st">"S01"</span>, t <span class="sc">&lt;=</span> <span class="dv">37</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>pbs_fc <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ATC2 <span class="sc">==</span> <span class="st">"S01"</span>)  <span class="sc">|&gt;</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(s01) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> s01 <span class="sc">|&gt;</span> <span class="fu">filter</span>(t <span class="sc">==</span> <span class="dv">37</span>), <span class="fu">aes</span>(<span class="at">x =</span> Month, <span class="at">y =</span> Scripts)) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Scripts (thousands)"</span>,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Forecast of S01 scripts: Feb 2006"</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-timeseries_files/figure-html/s01plot0-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The shaded regions show 80% and 95% prediction intervals for the forecast distribution. The observation is outside the 95% prediction interval, indicating that it is a possible anomaly. The surprisal probability in this case is about 0.003.</p>
<p>So far, we have just produced forecasts for time <span class="math inline">t=37</span>, using a training set comprising data up to time <span class="math inline">t=36</span>. This process is repeated as we increase the size of the training set. The following code block carries out the calculations in a loop.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>compute_pbs_scores <span class="ot">&lt;-</span> <span class="cf">function</span>(pbs) {</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  pbs<span class="sc">$</span>prob <span class="ot">&lt;-</span> <span class="cn">NA_real_</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Loop over all time periods starting with I=36</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq</span>(<span class="dv">36</span>, <span class="fu">max</span>(pbs<span class="sc">$</span>t) <span class="sc">-</span> <span class="dv">1</span>)) {</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Fit ETS model to all series up to time i and compute 1-step forecasts</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    pbs_fc <span class="ot">&lt;-</span> pbs <span class="sc">|&gt;</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(t <span class="sc">&lt;=</span> i) <span class="sc">|&gt;</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">model</span>(<span class="at">ets =</span> <span class="fu">ETS</span>(Scripts)) <span class="sc">|&gt;</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">rename</span>(<span class="at">fcast =</span> Scripts)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate surprisal probabilities from observations in time i+1</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    pbs_scores <span class="ot">&lt;-</span> pbs <span class="sc">|&gt;</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(t <span class="sc">==</span> i <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">right_join</span>(pbs_fc, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Month"</span>, <span class="st">"ATC2"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">surprisal_prob =</span> <span class="fu">surprisals</span>(Scripts, <span class="at">distribution =</span> fcast)) <span class="sc">|&gt;</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(Month, ATC2, surprisal_prob)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add probabilities to pbs data set</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>    pbs <span class="ot">&lt;-</span> pbs <span class="sc">|&gt;</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>      <span class="fu">left_join</span>(pbs_scores, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Month"</span>, <span class="st">"ATC2"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">prob =</span> <span class="fu">if_else</span>(<span class="sc">!</span><span class="fu">is.na</span>(surprisal_prob), surprisal_prob, prob)) <span class="sc">|&gt;</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(<span class="sc">-</span>surprisal_prob)</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(pbs)</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>pbs_scores <span class="ot">&lt;-</span> <span class="fu">compute_pbs_scores</span>(pbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will identify as anomalies any observations with a surprisal probability less than 1 in 1000.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>pbs_anomalies <span class="ot">&lt;-</span> pbs_scores <span class="sc">|&gt;</span> <span class="fu">filter</span>(prob <span class="sc">&lt;</span> <span class="fl">0.001</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>pbs_anomalies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tsibble: 282 x 5 [1M]
#&gt; # Key:       ATC2 [80]
#&gt;    ATC2     Month Scripts     t         prob
#&gt;    &lt;chr&gt;    &lt;mth&gt;   &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt;
#&gt;  1 A01   2004 Mar    14.1   153 0.000812    
#&gt;  2 A01   2005 Dec    18.2   174 0.000435    
#&gt;  3 A01   2007 Dec    15.5   198 0.0000385   
#&gt;  4 A02   2001 Nov   946.    125 0.0000351   
#&gt;  5 A02   2008 Feb  1288.    200 0.000000144 
#&gt;  6 A03   1998 Jan    93.9    79 0.000919    
#&gt;  7 A03   1999 Mar    94.6    93 0.000551    
#&gt;  8 A03   2000 Sep    81.4   111 0.000412    
#&gt;  9 A03   2000 Dec    72.5   114 0.0000000191
#&gt; 10 A03   2001 Nov    58.4   125 0.00000212  
#&gt; # ℹ 272 more rows</code></pre>
</div>
</div>
<p>Now let’s look at the A12 series that we started with, and consider the times where anomalies occur.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbs_plot</span>(pbs, pbs_anomalies, <span class="st">"A12"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-timeseries_files/figure-html/pbs_scores4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>One potential anomaly is identified in 2002, and the sudden drop at the start of 2006 causes several anomalies indicating a series of unusual observations. Eventually the “new normal” leads to fewer and fewer observations being labelled as anomalies.</p>
<p>This process of model adjustment is much faster in this next example, where the first jump leads to two anomalies, and then the second much larger jump leads to two more anomalies. After that, the model has learned to allow for large jumps in the series, so the later jump is not seen as anomalous.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbs_plot</span>(pbs, pbs_anomalies, <span class="st">"N07"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-timeseries_files/figure-html/pbs_scores5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The next example shows less dramatic anomalies that would be harder to identify without a model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbs_plot</span>(pbs, pbs_anomalies, <span class="st">"R05"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-timeseries_files/figure-html/pbs_scores6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The first anomaly in 1994 has an unusually large peak compared to the preceding years; the next two in 1997 precede an unusally low trough compared to the previous years; and the final two in 2004 coincide with a disruption to the seasonal pattern in that year.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-mstl" class="csl-entry" role="listitem">
Bandara, Kasun, Rob J Hyndman, and Christoph Bergmeir. 2022. <span>“<span>MSTL</span>: A Seasonal-Trend Decomposition Algorithm for Time Series with Multiple Seasonal Patterns.”</span> <em>International J Operational Research</em>. <a href="http://robjhyndman.com/publications/mstl/">http://robjhyndman.com/publications/mstl/</a>.
</div>
<div id="ref-Cleveland1990" class="csl-entry" role="listitem">
Cleveland, R B, W S Cleveland, J E McRae, and I J Terpenning. 1990. <span>“<span>STL</span>: A Seasonal-Trend Decomposition Procedure Based on Loess.”</span> <em>Journal of Official Statistics</em> 6 (1): 3–33. <a href="http://bit.ly/stl1990">http://bit.ly/stl1990</a>.
</div>
<div id="ref-Davies1993" class="csl-entry" role="listitem">
Davies, Laurie, and Ursula Gather. 1993. <span>“The Identification of Multiple Outliers.”</span> <em>Journal of the American Statistical Association</em> 88 (September): 782–92. <a href="https://doi.org/10.1080/01621459.1993.10476339">https://doi.org/10.1080/01621459.1993.10476339</a>.
</div>
<div id="ref-HMD" class="csl-entry" role="listitem">
Human Mortality Database. 2024. <span>“<span class="nocase">University of California, Berkeley (USA); Max Planck Institute for Demographic Research (Germany)</span>.”</span> <a href="https://www.mortality.org">www.mortality.org</a>.
</div>
<div id="ref-fpp3" class="csl-entry" role="listitem">
Hyndman, Rob J, and George Athanasopoulos. 2021. <em>Forecasting: Principles and Practice</em>. 3rd ed. Melbourne, Australia: OTexts. <a href="http://OTexts.org/fpp3">http://OTexts.org/fpp3</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/OTexts\.com\/weird");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08-highdim.html" class="pagination-link" aria-label="High-dimensional methods">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">High-dimensional methods</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-functional.html" class="pagination-link" aria-label="Functional data">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Functional data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Published by OTexts using <a href="https://quarto.org">Quarto</a>. <i class="fa-solid fa-copyright" aria-label="copyright"></i> <a href="https://robjhyndman.com">Rob J Hyndman</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>